# Generated by Django 5.0.14 on 2026-09-10 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant')], max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimatorSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_category', models.CharField(choices=[('residential', 'Residential Construction'), ('commercial', 'Commercial Construction'), ('renovation', 'Renovation & Remodeling'), ('project_management', 'Project Management')], db_index=True, max_length=50)),
                ('floor_area_sqm', models.FloatField(help_text='Estimated total area in square meters')),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('finish_quality', models.CharField(choices=[('standard', 'Standard Quality'), ('premium', 'Premium / Contemporary'), ('luxury', 'High-End Luxury')], default='standard', max_length=30)),
                ('estimated_materials_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_management_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_total_low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_total_high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
