# Generated by Django 5.0.14 on 2026-09-07 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='ESHAG Building and Construction', max_length=255)),
                ('brand_name', models.CharField(default='ESHAG', max_length=100)),
                ('tagline', models.CharField(default='Building Dreams. Constructing Futures.', max_length=255)),
                ('primary_domain', models.URLField(default='https://eshag.construction')),
                ('primary_phone', models.CharField(default='059 953 5884', max_length=50)),
                ('secondary_phone', models.CharField(default='024 139 5502', max_length=50)),
                ('whatsapp_number', models.CharField(default='059 953 5884', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@eshag.construction', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='Accra', max_length=100)),
                ('region', models.CharField(blank=True, default='Greater Accra', max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('business_hours', models.CharField(blank=True, default='Mon - Fri: 8:00 AM - 5:00 PM', max_length=255)),
                ('google_maps_embed_url', models.TextField(blank=True)),
                ('instagram_handle', models.CharField(default='@eshagbuildingandconst', max_length=100)),
                ('instagram_url', models.URLField(default='https://instagram.com/eshagbuildingandconst')),
                ('tiktok_handle', models.CharField(default='@eshagbuildingandconst', max_length=100)),
                ('tiktok_url', models.URLField(default='https://tiktok.com/@eshagbuildingandconst')),
                ('youtube_handle', models.CharField(default='@eshagbuildingandconst', max_length=100)),
                ('youtube_url', models.URLField(default='https://www.youtube.com/@eshagbuildingandconst')),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('footer_text', models.TextField(default='ESHAG Building and Construction is committed to delivering excellence, precision, and durability across all commercial and residential developments.')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g., Projects Completed', max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, help_text="e.g., '+' or '%'", max_length=10)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
